from . import breathing_processing
from . import cancer_screening_processing
from . import chest_pain_processing
from . import claudification_processing
from . import eye_processing
from . import general_health_processing
from . import genereal_pain_processing
from . import hearing_processing
from . import medication_processing
from . import mouth_processing 
